name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - master

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Yarn Install
        run: |
          yarn install
          yarn install istanbul coveralls

      - name: Test
        run: yarn run travis-test
